- src/Cornelis/InfoWin.hs
- src/Lib.hs
- stack.yaml
I've skimmed over your code and I think that `closeInfoWindows` would also error if you have windows open where your plugin doesn't set the `cornelis_window` buffer variable. Otherwise I'll have to dive deeper to fix your issue: https://github.com/neovimhaskell/nvim-hs/issues/94
> Handle buffer variable not being set

- default.nix
- flake.lock
- flake.nix
This lets Nix users who aren't using flakes easily install the package using e.g.
```bash
nix-env -f https://github.com/isovector/cornelis/archive/master.tar.gz -iA defaultPackage.x86_64-linux
```
If you want to try that out before merging, use: `https://github.com/masaeedu/cornelis/archive/add-flake-compat.tar.gz` instead.
> Add `flake-compat`

- README.md
- autoload/cornelis.vim
When opening a file, by default Cornelis prints the list of all available bindings: 
while this is useful, it may get tedious to see at every startup.  This PR introduces a configuration option to silence these messages: just add 
```vimrc
let g:cornelis_silent_remap = 1
```
to your `.vimrc` or, in lua,
``` lua
vim.g.cornelis_silent_remap = 1
```
> feature: optionally silence binding remapping messages

- README.md
- src/Cornelis/Types/Agda.hs
- src/Plugin.hs
I was missing features from `:CornelisNormalize`, so tried my hands at implementing them:
1. The command now accepts an optional compute mode, similarly to `:CornelisTypeContext` and friends.
2. When executed from within a hole, hole contents are normalized in that hole's context.
Please tell if these are features you'd like to see in `cornelis` and whether they require any adjustments :)
Thank a lot for your hard work, it is much appreciated!
> New `:CornelisNormalize` features: custom compute modes & normalization in holes

- README.md
- src/Cornelis/Agda.hs
- src/Cornelis/Config.hs
- src/Cornelis/InfoWin.hs
- src/Cornelis/Types.hs
- src/Lib.hs
I'm fairly picky about where my error/info windows appear in my editor, so having extra knobs to tweak beyond just "use `split`" and "use `vsplit`" will be useful.
Signed-off-by: Cameron Wong <cam@camdar.io>
> Add further customization options for info window placement

- src/Cornelis/Agda.hs
Looks like we missed one in a47993e.
Signed-off-by: Cameron Wong <cam@camdar.io>
> bugfix: stop hiding [Left]/[Right] from [Cornelis.Types]

- README.md
- agda-input.vim
- autoload/cornelis.vim
More customization options can't hurt. I find my `LocalLeader` to be irritating to hit while typing, but enough other, unrelated bindings use it that I'm not comfortable changing it wholesale.
> Allow agda-input prefixes other than <LocalLeader>

- README.md
- src/Lib.hs
- src/Plugin.hs
- test/Hello.agda
- test/TestSpec.hs
`Cmd_give` and friends are useful when attempting to fill holes, since they print errors explaining why unification failed.
I implemented "Give" and "Elaborate goal", and added the ability to abort a command (since I tend to accidentally normalize huge terms).
The last commit adds some documentation for all commands and points to the Emacs agda-mode equivalents.
> More commands: `:CornelisGive`, `:CornelisElaborate` and `:CornelisAbort`

- src/Cornelis/Types.hs
Agda HEAD seems to return certain normalizations in `GoalSpecific` with kind `NormalForm` as seen [here](https://github.com/agda/agda/blob/cd10c87aed3305945827a911c86e2718bbb00a5f/src/full/Agda/Interaction/JSONTop.hs#L376).
This previously led to a nasty display when running `CornelisNormalize` inside of a goal.
Signed-off-by: Cameron Wong <cam@camdar.io>
> Fix parsing of [NormalForm] in [DisplayInfo]

- src/Cornelis/Pretty.hs
Some errors are not fatal and still allow further interaction. Also make the highlighting easier on the eyes by highlighting only the first line of each message.
> Render goals even when errors are reported

- src/Cornelis/Agda.hs
- src/Cornelis/Types.hs
- agda sometimes likes outputing empty lines
- get only one thread to write to agda to avoid concurrent interleavings
> Make IO with agda more robust

- src/Cornelis/Goals.hs
- src/Cornelis/Highlighting.hs
- src/Cornelis/Types.hs
- src/Cornelis/Vim.hs
- src/Lib.hs
- src/Plugin.hs
This PR attaches extmarks to interaction points, and looks them up at runtime to determine a goal's interval. This fixes a bunch of weird bugs where the buffer would have changed and we'd compute the wrong thing to replace. Additionally, it gets rid of a BIG HACK, which is always nice.
Agda sends intervals that span interaction points, which we were using as the source of truth for where goals actually are in the document. But there's a better way: extmarks! Extmarks are attached to the buffer when we do syntax highlighting, and track changes to the document when we do edits. Therefore, the intervals spanned by extmarks are a much better source of truth than the intervals that come from Agda. As a bonus, we don't need to do any logic to try to keep the two in sync.
Unfortunately life …
> Correctly track interaction points via extmarks

- cornelis.cabal
- flake.lock
- ftplugin/agda.vim
- package.yaml
- src/Cornelis/Agda.hs
- src/Cornelis/Debug.hs
- src/Cornelis/Diff.hs
- src/Cornelis/Highlighting.hs
- src/Cornelis/Offsets.hs
- src/Cornelis/Types.hs
- src/Lib.hs
- src/Plugin.hs
- stack.yaml
- stack.yaml.lock
1. We need to know exactly what text Agda has loaded, so now  `CornelisLoad` checks whether Agda is busy, and saves on load
2. We also record the interval map from `Cornelis.Highlighting` at the time of loading, and from then we record all changes to the buffer using the newly released [diff-loc library](https://hackage.haskell.org/package/diff-loc), which then maps outdated highlighting spans from Agda across those changes.
> Handle highlighting on modified source

- README.md
- src/Cornelis/Config.hs
- src/Cornelis/InfoWin.hs
- src/Cornelis/Types.hs
This commit alows you to configure the width of the info window as well as the height. It also sets the filetype of the info window (as lean.nvim does), which allows for future syntax highlighting and easier scriptability using autocommands.
I also cleaned up a few things that HLS was complaining about, but I'm happy to save those changes for another commit.
> Allow configuring infoview width

- .github/template/stack-cache/action.yml
- .github/workflows/ci.yml
- .github/workflows/nix-agda.yml
- .github/workflows/nix.yml
- .github/workflows/stack.yml
- flake.lock
- flake.nix
- stack.yaml
- stack.yaml.lock
* Updated to latest LTS, and made required changes to flake and CI.
* Changed CI to use Nix to install test dependencies (Neovim and Agda) on Linux/macOS so that the two share the same process for installing deps, and don't ever need to build Agda.
* Changed some stuff about caching works to reduce the amount of new caches that are created.
> Update resolver, simplify CI, and reduce CI average runtime

- README.md
- src/Cornelis/Goals.hs
- src/Cornelis/Pretty.hs
- src/Cornelis/Types.hs
- src/Lib.hs
- src/Plugin.hs
- test/Hello.agda
- test/TestSpec.hs
This implements functionality to infer the type of an expression, the equivalent of Emacs <kbd>C-c</kbd><kbd>C-d</kbd>.  When inside of a hole it infers the type of the hole contents, or prompts for input. Outside of a hole it always prompts for an expression.
I've added `withGoalContentsOrPrompt` to `Cornelis.Goal` that deals with the common pattern of "use contents of a hole if available, otherwise prompt for input". Other commands could be refactored to use this, if wanted.
---
I'm marking this as a draft since I am running into an error when parsing Agda's reply. I am not sure whether this is a bug in Agda v2.6.2.2, or caused by not properly decoding the response. Any help would be appreciated.
In a file
```agda
data Void : Set where
```
Running `:CornelisTypeInfer` and putting `Void` …
> Infer type of expression using `:CornelisTypeInfer`

- flake.lock
- flake.nix
- stack.yaml
- stack.yaml.lock
- Use `nvim-hs` version 2.3.2.2
- Update LTS and Nix flake inputs
> Fix Nix build and update Stack resolver and Nix flake inputs

- README.md
- src/Cornelis/Goals.hs
- src/Cornelis/Highlighting.hs
- src/Cornelis/Pretty.hs
- src/Plugin.hs
- syntax/agda.vim
- test/TestSpec.hs
I've been using this to customize Agda highlighting for a while now, maybe it's a good idea to upstream.
---
Instead of attaching Neovim-builtin highlight groups (`Type`, `Identifier`, `Todo`, ...) directly to locations in the buffer, attach cornelis-specific highlight groups.  These groups are linked to builtin HL groups by default, but can be overridden in a user's configuration.
For example, the HL group of holes is linked to `Todo` by default:
https://github.com/isovector/cornelis/blob/a2c551765b29d6446df3ef8c4edde297adeb5c95/syntax/agda.vim#L16-L17
...but in my personal configuration I use
```vim
highlight CornelisHole ctermfg=yellow ctermbg=NONE cterm=undercurl
```
This is inspired by other plugins that have customizable highlighting, such as …
> User-customizable highlighting

- flake.nix
`buildVimPluginFrom2Nix` is deprecated: use `buildVimPlugin` instead
> `buildVimPluginFrom2Nix` is deprecated

- .github/template/stack-cache/action.yml
- .github/workflows/nix-agda.yml
- .github/workflows/nix.yml
- .github/workflows/stack.yml
- flake.lock
- flake.nix
- stack.yaml
- stack.yaml.lock
- **Update to GHC 9.6.4**
- **Update to latest version of GitHub actions used**
> Update to GHC 9.6.4

- flake.nix
Haskell derivations are notoriously large. Putting the final binary into its own output (`bin`) reduces the package closure size from ~1GiB to ~60MiB. The default output for installation is now `cornelis.bin`, but all other build artifacts are still available in `cornelis.out`, cf. [the manual](https://nixos.org/manual/nixpkgs/stable/#haskell-packaging-helpers).
> Reduce closure size of Nix derivation

- src/Plugin.hs
- test/Readonly.agda
- test/TestSpec.hs
Previously, loading buffers of read-only files wasn't possible, as cornelis would try to write the file before loading (which would fail and abort the command).
Add `silent` to the command to ignore failed writes.  This should be a safe fallback.
Fixes #116.
> Ignore failed writes when loading buffer

- src/Cornelis/Types/Agda.hs
- src/Lib.hs
- src/Plugin.hs
With version 2.7.0 of Agda and the introduction of mimer (instead of agsy) for auto mode, Cmd_autoOne comes with arguments:
```haskell
-- | Solve (all goals / the goal at point) by using Mimer proof search.
| Cmd_autoOne  Rewrite   InteractionId range String
```
(see https://github.com/agda/agda/blob/11e54c0e0229996c22ed7b53a50694933de84b09/src/full/Agda/Interaction/Base.hs#L174 for reference). This is an inconsitency between agda and cornelis types for interaction and brakes cornelis command :CornelisAuto which throws an error. 
The proposed change to the repository fixes the issue and creates type consistency between cornelis and agda Interaction datatype.
> autoOne functionality update for Agda v2.7.0 and up

- README.md
There are some incompatibilities between Cornelis and the <HEAD> version of Agda, so before I make any breaking changes I'd like to create a tag policy.
> add tagging policy and lazy instructions

- src/Cornelis/Pretty.hs
- src/Cornelis/Types.hs
When refining a goal whose type is a `data` type, and if there is more than one matching constructor, Agda replies with a list of possible constructors to introduce.  We parse this reply and display the list of constructors in the info view.  This fixes #141.
> Display list of possible constructors to introduce
